"""init

Revision ID: e914d5ecbb68
Revises: 
Create Date: 2025-11-29 10:43:16.356683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e914d5ecbb68'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('bug_statuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bug_statuses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bug_statuses_slug'), ['slug'], unique=True)

    op.create_table('task_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('task_statuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_statuses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_statuses_slug'), ['slug'], unique=True)

    op.create_table('bugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['bug_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bugs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bugs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bugs_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_bugs_title'), ['title'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['task_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_tasks_title'), ['title'], unique=False)

    op.create_table('bug_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bug_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bug_id'], ['bugs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bug_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bug_activities_id'), ['id'], unique=False)

    op.create_table('bug_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bug_id', sa.Integer(), nullable=True),
    sa.Column('change_type', sa.String(), nullable=True),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bug_id'], ['bugs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bug_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bug_history_id'), ['id'], unique=False)

    op.create_table('bug_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bug_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bug_id'], ['bugs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bug_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bug_links_id'), ['id'], unique=False)

    op.create_table('task_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_activities_id'), ['id'], unique=False)

    op.create_table('task_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('change_type', sa.String(), nullable=True),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_history_id'), ['id'], unique=False)

    op.create_table('task_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_links_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_links_id'))

    op.drop_table('task_links')
    with op.batch_alter_table('task_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_history_id'))

    op.drop_table('task_history')
    with op.batch_alter_table('task_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_activities_id'))

    op.drop_table('task_activities')
    with op.batch_alter_table('bug_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bug_links_id'))

    op.drop_table('bug_links')
    with op.batch_alter_table('bug_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bug_history_id'))

    op.drop_table('bug_history')
    with op.batch_alter_table('bug_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bug_activities_id'))

    op.drop_table('bug_activities')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_title'))
        batch_op.drop_index(batch_op.f('ix_tasks_slug'))
        batch_op.drop_index(batch_op.f('ix_tasks_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('bugs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bugs_title'))
        batch_op.drop_index(batch_op.f('ix_bugs_slug'))
        batch_op.drop_index(batch_op.f('ix_bugs_id'))

    op.drop_table('bugs')
    with op.batch_alter_table('task_statuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_statuses_slug'))
        batch_op.drop_index(batch_op.f('ix_task_statuses_id'))

    op.drop_table('task_statuses')
    with op.batch_alter_table('bug_statuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bug_statuses_slug'))
        batch_op.drop_index(batch_op.f('ix_bug_statuses_id'))

    op.drop_table('bug_statuses')
    # ### end Alembic commands ###
